input: touchscreen: lge_qos: make `pp` static
It causes duplicate symbol issue:
ld.lld: error: duplicate symbol: pp
>>> defined at touch_pen.c:22 (/mnt/data/ssd1/build/lineage-21/out/target/product/caymanslm/obj/KERNEL_OBJ/../../../../../../kernel/lge/sdm845/drivers/input/touchscreen/lge_qos/touch_pen.c:22)
>>>            drivers/built-in.o:(pp)
>>> defined at swr-wcd-ctrl.c:72 (/mnt/data/ssd1/build/lineage-21/out/target/product/caymanslm/obj/KERNEL_OBJ/../../../../../../kernel/lge/sdm845/techpack/audio/soc/swr-wcd-ctrl.c:72)
>>>            techpack/built-in.o:(.data+0x69D14)

This variable only ever gets touched within this file, so keep it
there.

Change-Id: I8dcde13984b4c4cac80c3cb067e5298014a8f877
Signed-off-by: Han Sol Jin <hansol@hansol.ca>